### PR TITLE
Deprecate in favour of https://github.com/istanbuljs/babel-plugin-ist…

### PR DESCRIPTION
**Pull request by graingert**
…anbul

### CODE REVIEW

**Comment by izaakschroeder** [comment]
The mechanism by which `adana` and `instabul` instrument/analyze things is somewhat different (for example adana's `ignore` mechanism is based on tagging instead of skipping instrumentation). I'm happy to add a link to though!

**Comment by graingert** [comment]
Fair will update pr

**Comment by graingert** [comment]
I was under the impression this was functionally exactly the same. Can you go into more detail about whats different?

**Comment by izaakschroeder** [comment]
There are a lot of similarities and I started this plugin when `istanbul` had nothing for `babel` so the functionality is close. However, there is a use case that `istanbul` doesn't cover that I wanted which is instrumentation tagging.

Normally you would ignore this block in `instanbul` because your coverage will go down testing in a particular browser:

``` js
if (ie9) {
  // ...
} else {
  // ...
}
```

I wanted to ensure this could be dealt with and so adana offers tagging.

``` js
if (ie9) /* adana: +ie */ {
  // Everything in this block, including the branch above, is tagged with "ie"
  // ...
} else {
  // ...
}
```

With this mechanism you can tell coverage to look only at certain tags or exclude others. So when you test against normal browsers you drop all instrumentation data tagged with `ie`. This lets you cover things you otherwise wouldn't be able to.

Additionally the line coverage mechanism adana has is quite different too. There is no line counter in instrumented code – the line count is done post-mortem. This let's you defer your line count metric and do things like say "if not all branches were executed on this line, consider it to be 0". For some tools that don't record branch information (coveralls) this can be a useful tool to short-circuit the task of finding where your coverage is missing.

Indeed it's not as mature as istanbul but I use it on my projects and it's been doing an excellent job so I see no need to throw it out just yet. 😄

**Comment by izaakschroeder** [comment]
Closing due to inactivity.

**Pull request closed without merging**
